### ISSUE TITLE
French crashes with "Segmentation fault" on windows

### ISSUE THREAD

**Issue by hissalht** [axa-group/nlp.js#177] opened 2019-04-30 09:00 UTC
**Describe the bug**
Processing a string using french (fr) crashes node with no error message.

**To Reproduce**
Run this code in nodeJS :
```javascript
const { NlpManager } = require('node-nlp')

const LANG = 'fr'
const ACTION_STOP = 'actions.stop'
const ACTION_TURN_LEFT = 'actions.turnLeft'
const ACTION_TURN_RIGHT = 'actions.turnRight'

const manager = new NlpManager({ languages: [LANG] })

manager.addDocument(LANG, 'stop', ACTION_STOP)
manager.addDocument(LANG, 'arretez-vous', ACTION_STOP)

manager.addDocument(LANG, 'tournez à gauche', ACTION_TURN_LEFT)
manager.addDocument(LANG, 'prendre à gauche', ACTION_TURN_LEFT)
manager.addDocument(LANG, 'tournez à droite', ACTION_TURN_RIGHT)
manager.addDocument(LANG, 'prendre à droite', ACTION_TURN_RIGHT)

;(async() => {
    await manager.train();
    console.log('trained')
    manager.save();
    console.log('saved')
    manager.process('Tourner à droite')
      .then(console.log)
      .catch(console.log)
})()
```

**Expected behavior**
The result is logged into the console. Or some king of exception is thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/7683740/56950777-909b1780-6b36-11e9-829c-2fc32e2f6530.png)
EDIT: when running the script without nodemon, I get a "Segmentation fault"
![image](https://user-images.githubusercontent.com/7683740/56952448-ab6f8b00-6b3a-11e9-8cb9-fd6880ea2a6b.png)

**Desktop (please complete the following information):**
- OS Name Microsoft Windows 10 Enterprise
- Version 10.0.17134 Build 17134
 - NodeJS v10.15.3

**Additional context**
In the provided code, using any language but french (I didnt test all of them tho) makes the script "work" and gives some results.

EDIT: add specific windows version

**Comment by hissalht** [comment] 2019-04-30 09:25
I asked a coworker to run the same example on his machine and it worked. He was on macOS though, and using a previous version of node...

**Comment by jesus-seijas-sp** [comment] 2019-05-02 18:11
Hello, I'm trying to reproduce the issue with exactly same SO (Windows 10 pro) and same Node version, but I'm not able to reproduce the issue...

**Comment by hissalht** [comment] 2019-05-03 09:00
I tried it on my personnal machine at home (W10 Home I think) and on another machine from work (W10 pro), still no results displayed.

Changing the language to anything not french (or just the one used in `manager.process()`) still prints some results.

Note: the "Segmentation fault" only appears in the bash terminal from VSCode. It still does not give any result on other terminals (cmd, powershell, git-bash).

**Comment by jesus-seijas-sp** [comment] 2019-05-06 06:44
Hello again,

As an idea... if only crash in french, then propably the problem will be at the stemmer. Can you try with the alternative stemmer? Is to add the requirement to NlpUtil and add this line:

```javascript
NlpUtil.useAlternative.fr = true;
```

```javascript
const { NlpManager, NlpUtil } = require('node-nlp')

const LANG = 'fr'
const ACTION_STOP = 'actions.stop'
const ACTION_TURN_LEFT = 'actions.turnLeft'
const ACTION_TURN_RIGHT = 'actions.turnRight'

NlpUtil.useAlternative.fr = true;
const manager = new NlpManager({ languages: [LANG] })

manager.addDocument(LANG, 'stop', ACTION_STOP)
manager.addDocument(LANG, 'arretez-vous', ACTION_STOP)

manager.addDocument(LANG, 'tournez à gauche', ACTION_TURN_LEFT)
manager.addDocument(LANG, 'prendre à gauche', ACTION_TURN_LEFT)
manager.addDocument(LANG, 'tournez à droite', ACTION_TURN_RIGHT)
manager.addDocument(LANG, 'prendre à droite', ACTION_TURN_RIGHT)

;(async() => {
    await manager.train();
    console.log('trained')
    manager.save();
    console.log('saved')
    manager.process('Tourner à droite')
      .then(console.log)
      .catch(console.log)
})()
```

This will change the stemmer to the alternative one based on Snowball, so the code is totally different.

**Comment by hissalht** [comment] 2019-05-06 07:56
Unfortunately, `NlpUtil.useAlternative.fr = true;` did not change anything 🤔

**Comment by jesus-seijas-sp** [comment] 2019-09-30 20:00
Hello @hissalht it seems that the problem comes from the builtin entity extraction, it fails on some windows systems when extracting french entities.

Try to initialize the manager like this, and will not execute the builtin extraction. If you need builtin extraction I suggest you to use the Duckling integration.
```javascript
  const manager = new NlpManager({ languages: ['fr'], nlu: { log: true }, ner: { builtins: [] }});
```

**Comment by jesus-seijas-sp** [comment] 2020-08-11 15:43
Closing. This issue is caused by one of the packages: https://www.npmjs.com/package/@microsoft/recognizers-text-suite
Alternatives: not use builtins or use duckling instead

**Closed by jesus-seijas-sp** 2020-08-11 15:43 UTC
