### ISSUE TITLE
Not able to trigger the "None" intent when using allowList

### ISSUE THREAD

**Issue by shubhamtibra** [axa-group/nlp.js#953] opened 2021-07-19 05:32 UTC
**Describe the bug**
Not able to trigger the None intent when using allowList. Even if no words match with the input, classification is still giving a result from the allowList.

**To Reproduce**

```
const { NlpManager } = require('node-nlp');
const manager = new NlpManager({ languages: ['en'] });

manager.addDocument('en', "ask pricing", 'ask.pricing');
manager.addDocument('en', 'ask product', 'ask.product');
manager.addDocument("en", "get details", "get.pricing.details");
manager.addDocument("en", "get details", "get.product.details");

output = await manager.process("hi", undefined, undefined, {allowList: ["ask.pricing", "ask.product", "None"]});
```

**Expected behavior**
Since the input text "hi" doesn't match with 'ask.pricing' and  'ask.product', the output should be None Intent.

**Screenshots**

<img width="606" alt="Screenshot 2021-07-19 at 11 00 57 AM" src="https://user-images.githubusercontent.com/9497860/126107728-7d5732c3-9d92-4ff3-afe6-7b694a023475.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, ubuntu, windows]
 - Package version [e.g. 22]
 - Node version [e.g. 12]

**Additional context**

**Comment by reinoute** [comment] 2021-08-03 12:44
Could be a duplicate of [the issue that I reported here](https://github.com/axa-group/nlp.js/issues/954). Which would mean it's not necessarily related to `allowList`.

**Comment by dbatistat** [comment] 2021-09-29 14:29
Try to use:

```
const { NlpManager } = require('node-nlp');
const manager = new NlpManager({ languages: ['en'], nlu: { useNoneFeature: true, spellCheck: true } });

manager.addDocument('en', "ask pricing", 'ask.pricing');
manager.addDocument('en', 'ask product', 'ask.product');
manager.addDocument("en", "get details", "get.pricing.details");
manager.addDocument("en", "get details", "get.product.details");

output = await manager.process("hi", undefined, undefined, {allowList: ["ask.pricing", "ask.product", "None"]});
```

**Comment by aigloss** [comment] 2022-11-24 13:09
Closing due to inactivity. Please, re-open if you think the topic is still alive.

**Closed by aigloss** 2022-11-24 13:09 UTC
