### ISSUE TITLE
Stop word feature not workin

### ISSUE THREAD

**Issue by NadherBB** [axa-group/nlp.js#160] opened 2019-03-27 18:29 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by NadherBB** [comment] 2019-03-27 18:33
Hi there,

I want to ask you why stop words i mentionned are not deleted while training my bot. 
I'm am using english or french language, and i suppose that words like "le" or "cette" are not supposed to appear in the nlp model with an important weight on each intent.

could you explain to me how it works ?

Thanks ,

**Comment by jesus-seijas-sp** [comment] 2019-03-27 18:43
Hi, 
In the manager you can access the classifiers by language. In each classifier you can decide to keep the stopwords or remove them. By default, keepStopWords is true.
You can execute the example code here: https://runkit.com/embed/te2qarpa1o2g

```javascript
const { NlpManager } = require("node-nlp");
const manager = new NlpManager({ languages: ['fr'] });
const classifier = manager.classifiers['fr'];
let result = classifier.tokenizeAndStem('Je vais regarder la télé ce soir');
console.log(result);
// ["je", "vais", "regard", "la", "tel", "ce", "soir"]
classifier.settings.keepStopWords = false;
result = classifier.tokenizeAndStem('Je vais regarder la télé ce soir');
console.log(result);
// ["je", "vais", "regard", "tel", "soir"]
```

**Comment by NadherBB** [comment] 2019-03-28 16:35
Hi Jesus,

Thanks for you feedback, the problem with my model occures when training some big models where intents have more then 30 utterence.

you can find attached the nlp manager where words like "je" are not deleted as it figure in  the stop words list.

Could you please check this .

Best regards,
[modelnlptestecom4.txt](https://github.com/axa-group/nlp.js/files/3019143/modelnlptestecom4.txt)

**Comment by jesus-seijas-sp** [comment] 2019-03-28 19:15
Hello,

I investigated why je was not removed... the problem is that it is case sensitive! So you can try training with the lowercase version of the texts.

Also, this is a bug, the stopword system must not be case sensitive.

**Comment by jesus-seijas-sp** [comment] 2019-04-17 17:28
Hello @NadherBB 
This issue was fixed in version 3.x, so now you can have stop words working.

**Comment by jesus-seijas-sp** [comment] 2019-04-23 09:04
Closed as solved in version 3.x

**Closed by jesus-seijas-sp** 2019-04-23 09:04 UTC

**Comment by GuillermoPena** [comment] 2020-12-18 16:46
How use tokenizeAndStem in v4.x? I can't access to classifiers.
Regards

**Comment by jesus-seijas-sp** [comment] 2020-12-18 16:55
@GuillermoPena try this: https://github.com/axa-group/nlp.js/issues/757
