### ISSUE TITLE
Big Amount of data big delay train

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#213] opened 2019-07-03 19:31 UTC
**Describe the bug**
4 days pass to train 415703 inputs ?? and its not done yet..

**To Reproduce**
![image](https://user-images.githubusercontent.com/17410205/60619464-20677700-9daf-11e9-8457-2417fc27a756.png)

**Expected behavior**
It took 35 hours just to load all data

**Desktop **
 - OS: Windows 10
 - Browser Node JS 10.15
 - Version latest

PC info : 
CPU : Core i7 4770 @3.40 GHz
Ram : 16 GB 
GPU : GTX 750

![image](https://user-images.githubusercontent.com/17410205/60619738-b6030680-9daf-11e9-8fcc-4a46e3fec539.png)

![image](https://user-images.githubusercontent.com/17410205/60619775-c1eec880-9daf-11e9-978a-ad25c808ef80.png)

Its normal for that amont of data ???

**Comment by jesus-seijas-sp** [comment] 2019-07-04 07:02
Hello:
Look at the limits of other vendors. Example, Microsoft LUIS, the limits are a maximum of 15.000 utterances, 499 intents. You are trying to train something with 415703 that is something totally abnormal when we are talking about a chatbot. Take into account that if you have this ammount of utterances, you probably have a lot of features (different words) and a lot of intents, so your amount of variables will be huge, and every epoch of the neural network you are modifying this huge amount of variables for each one of your utterances... 

Even with that, it is possible to do it, take a look into this issue: https://github.com/axa-group/nlp.js/issues/206

**Comment by jesus-seijas-sp** [comment] 2019-07-15 22:08
You can also change the options to limit number of epochs or increase the minimum error.

**Comment by ran-j** [comment] 2019-07-15 22:22
Sorry for replying late, I was trying to conduct training with JS tensorflow but had a worse problem, memory overflow.

I need to train this absurd amount of data but I still do not know how, thanks for the response.

**Comment by Orfeous** [comment] 2019-07-17 18:49
Hi @ran-j ,

Why don't you try to break it into smaller chunks and train them separately?
Then when your bot "booting" you load the models one-by-one.

I'm also dealing with relatively big amount of data, and my approach is the one what i described above.
it works out well so far. Obviously it consumes a lot of memory but this is how the engine works. :)

/Gabor

**Comment by jesus-seijas-sp** [comment] 2019-07-17 23:12
Hi @ran-j , I uploaded a micro-optimization of the neural network, a training that I have that taked 40 secs (130 intents) now train in 17 secs. But it will not be enough.

As I said, the good optimization is to split into domains, so each domain will train separately, and the master domain will train so given an utterance it returns the domain. This improves the times a lot.
If the problem is that your data is so huge that it's impossible to split manually into domains, I have a pilot to automatically split corpus into domains the best way to improve trainings. Unfortunatelly I don't have such a big corpus as you have. Perhaps you can share your corpus with me so I can test this pilot with such a huge data and see if I can make it goes faster. So please feel free to contact me to provide the data.

Kind Regards,
Jesus

**Comment by ran-j** [comment] 2019-07-18 00:59
I'm trying a different training but it will never end kkkk.

![image](https://user-images.githubusercontent.com/17410205/61421552-eaadac80-a8dd-11e9-9eab-67cc8ac8effb.png)

**Comment by ran-j** [comment] 2019-07-18 01:01
@jesus-seijas-sp Sorry but this data is a little classified

**Comment by ran-j** [comment] 2019-07-18 01:12
If it helps I can test your  pilot

**Comment by ran-j** [comment] 2019-07-18 01:19
And here I go 
![image](https://user-images.githubusercontent.com/17410205/61422160-e0d97880-a8e0-11e9-898d-2b4384739027.png)

**Comment by jesus-seijas-sp** [comment] 2019-07-18 11:14
> I'm trying a different training but it will never end kkkk.
> 
> ![image](https://user-images.githubusercontent.com/17410205/61421552-eaadac80-a8dd-11e9-9eab-67cc8ac8effb.png)

Some feedback:
- You're creating one different domain for each intent, so you will have thousands of domains each one with one intent... that means thousands of neural networks that have only one option to classify... does not works like that.
- Based on the code it seems that you have only one utterance per intent... usually the recommendation is 5 per intent.
- I think that you're trying to use an NLP for chatbots for something that is crearly not a chatbot

If I cannot have access to the data then I'm sorry but I can't help, and also it means that the issue cannot be reproduced by anyone withot the data. 

On the other hand, I recommend you to read the papers and progress of SQuAD: https://rajpurkar.github.io/SQuAD-explorer/

SQuAD uses 100.000 Q&A, that's 5 times less than your problem, and the bigger F1-score that nobody got over this is 89.474... training with BERT+DAE+AoA. For this kind of training you'll need TPUs and patience (a pair of weeks to train). Given the fact that this is the current state of the art, and you're problem is over the current state of the art, I recommend you to contact with the research teams of the different universities working in this problem.

**Comment by ran-j** [comment] 2019-07-18 12:31
Ok I will study more, this is just a data test the real data it's bigger than this one, and have more params to one answer I was just testing if I cant train with half of data, becouse when I try with tensorflow JS I have a memory overflow.

**Comment by obaid** [comment] 2019-08-23 12:55
Hi @jesus-seijas-sp, can you explain how Domains would work in this case? I couldn't really find a good doc on it.

> As I said, the good optimization is to split into domains, so each domain will train separately, and the master domain will train so given an utterance it returns the domain. This improves the times a lot.

**Comment by jesus-seijas-sp** [comment] 2019-09-05 12:03
Hello, I've working on achieve the training of huge amounts of data, and with performance, and has been released as version 3.7.0. Also improvements in the time of run an input to get the classifications.

I've tested with 10k intents (1 utterance per intent) and takes around 30 minutes (29 epochs, 60 seconds per intent).

It's able to train 50k intents, but takes around 14 hours, and there is another problem: when saving into file, there is a JSON.stringify() to convert the object into string to save it.... the problem is that the javascript V8 haves a limitation in the heap memory for strings of aprox 1GB (2^30 - 25 bytes).

So i'm sorry, but even improving to train more than 50k, right now there is no way to save the training into file, the method to save should be replaced by one without using an intermediate string.

More on that, visiting different providers, it seems that the one with the higher limit of intents has 2000 intents, so being able to train and save more than 10k is a great achievement.

**Comment by ran-j** [comment] 2019-09-06 18:57
Wow.

I wonder there is a way to save in pieces the training and merge then when I start the server.

or I can try write  a c++ module to save this big amount of data, I just dont kwno if this would works kkkk

**Comment by jesus-seijas-sp** [comment] 2020-08-12 10:20
Closing. After the improvements, training of 10k intents is taking less than 4 minutes. But 415.703 is too much, taking into account that any commercial tool support up to 2.000.

**Closed by jesus-seijas-sp** 2020-08-12 10:20 UTC

**Comment by obaid** [comment] 2020-08-12 11:52
@jesus-seijas-sp is there a good example of using domains to breakdown large dataset?

**Comment by jesus-seijas-sp** [comment] 2020-08-12 11:59
@obaid To be honest, on years dedicated to this professionally, I never found a dataset so large that cannot be handle with 10k intents. In fact, Microsoft LUIS only supports 499, DialogFlow 2.000.

So to generate an example of that, someone have to provide me this huge dataset that fits in the problem of a chatbot. So feel free of provide me this dataset, so I can study it.

**Comment by obaid** [comment] 2020-08-12 12:01
Sounds good. I don't have the dataset yet (still working on preparing it). Will share it when it's ready. 

Also, any migration guide to go from 3.x to 4.x?

Thanks for a great library. :)
