### ISSUE TITLE
NlpManager behaviour changed

### ISSUE THREAD

**Issue by mheimschild** [axa-group/nlp.js#98] opened 2018-10-22 19:06 UTC
NlpManager produces false positives with score 1

sample code:

`const { NlpManager } = require('node-nlp');

const manager = new NlpManager({
  languages: ['de'],
});

manager.addDocument('de', 'ich will auto kaufen', 'buy');

(async () => {
  await manager.train();

  console.log(await manager.process('ich will auto kaufen'));
  console.log(await manager.process('ich habe hunger'));
})();
`

ver. 2.0.2 result
`{ locale: 'de',
  localeIso2: 'de',
  language: 'German',
  utterance: 'ich will auto kaufen',
  classification: [ { label: 'buy', value: 0.9975597509481738 } ],
  intent: 'buy',
  domain: 'default',
  score: 0.9975597509481738,
  entities: [],
  sentiment:
   { score: 0,
     comparative: 0,
     vote: 'neutral',
     numWords: 4,
     numHits: 0,
     type: 'senticon',
     language: 'de' } }
{ locale: 'de',
  localeIso2: 'de',
  language: 'German',
  utterance: 'ich habe hunger',
  classification: [ { label: 'buy', value: 0.8180665881599193 } ],
  intent: 'buy',
  domain: 'default',
  score: 0.8180665881599193,
  entities: [],
  sentiment:
   { score: -0.0565,
     comparative: -0.018833333333333334,
     vote: 'negative',
     numWords: 3,
     numHits: 1,
     type: 'senticon',
     language: 'de' } }`

with current version:
`{ locale: 'de',
  localeIso2: 'de',
  language: 'German',
  utterance: 'ich will auto kaufen',
  classification: [ { label: 'buy', value: 1 } ],
  intent: 'buy',
  domain: 'default',
  score: 1,
  entities: [],
  sentiment:
   { score: 0,
     comparative: 0,
     vote: 'neutral',
     numWords: 4,
     numHits: 0,
     type: 'senticon',
     language: 'de' } }
{ locale: 'de',
  localeIso2: 'de',
  language: 'German',
  utterance: 'ich habe hunger',
  classification: [ { label: 'buy', value: 1 } ],
  intent: 'buy',
  domain: 'default',
  score: 1,
  entities: [],
  sentiment:
   { score: -0.0565,
     comparative: -0.018833333333333334,
     vote: 'negative',
     numWords: 3,
     numHits: 1,
     type: 'senticon',
     language: 'de' } }`

**Comment by jesus-seijas-sp** [comment] 2018-10-22 19:14
Hi! 
This seems to be a collateral behaviour after we introduced a Binary Relevance Neural Network. We didn't take into account the case where only one intent exists, so the Binary Relevance only contains a possible target intent, and that means that this intent will score 1 if the Logistic Regression Classifier does not identify the utterance as being None.

You can return to the old behaviour by deactivating the Neural Network at settings:

```javascript
const manager = new NlpManager({
languages: ['de'],
useNeural: false
});
```

**Comment by mheimschild** [comment] 2018-10-28 08:38
Hi,
I got it but nevertheless - how to avoid false positives?

`const manager = new NlpManager({
	languages: ['en'],
	useNeural: false
});`

`manager.addDocument('en', 'goodbye for now', 'greetings.bye');
manager.addDocument('en', 'bye bye take care', 'greetings.bye');
manager.addDocument('en', 'okay see you later', 'greetings.bye');
manager.addDocument('en', 'bye for now', 'greetings.bye');
manager.addDocument('en', 'i must go', 'greetings.bye');
manager.addDocument('en', 'hello', 'greetings.hello');
manager.addDocument('en', 'hi', 'greetings.hello');
manager.addDocument('en', 'howdy', 'greetings.hello');`

`let response = await manager.process('how it the weather now?');`

recognises intent 'greetings.bye' with confidence > 0.9

`response = await manager.process('what time is it now?');`

recognises intent 'greetings.bye' with confidence > 0.9

I would rather expect intent None to be able to provide some neutral answer

**Comment by jesus-seijas-sp** [comment] 2018-10-28 09:46
This is happening because the Probability of Class caused by the "now".
I will explain, one the utterances are tokenized and stemmed, this is the frequency of words:

```
greetings.bye: {
        "bye": 3,
        "for": 2,
        "now": 2,
        "goodby": 1,
        "take": 1,
        "care": 1,
        "okai": 1,
        "see": 1,
        "you": 1,
        "later": 1,
        "i": 1,
        "must": 1,
        "go": 1,
}

greetings.hello: {
        "hello": 1,
        "hi": 1,
        "howdi": 1
}
```

Two of the observations for _greetings.bye_ contains "now", and none of the observations of the _greetings.hello_ contains it, so "now" is causing a big bias towards _greetings.bye_, because the amount of features is still very low, so every feature has a big weight inside the model. This does not happens in biggest models, because usually certain common words are repeated in several intents, so the weights are lower, and don't cause so huge bias towards one intent.

But even in small models you can avoid that to happen:

There are two approachs:
**First approach:** Don't include the "for now" in the utterances. Even without it, it will recognize utterances with goodboy towards greetings.bye.

```
  manager.addDocument('en', 'goodbye', 'greetings.bye'); 
  manager.addDocument('en', 'bye bye take care', 'greetings.bye'); 
  manager.addDocument('en', 'okay see you later', 'greetings.bye'); 
  manager.addDocument('en', 'bye', 'greetings.bye'); 
  manager.addDocument('en', 'i must go', 'greetings.bye'); 
  
  manager.addDocument('en', 'hello', 'greetings.hello'); 
  manager.addDocument('en', 'hi', 'greetings.hello'); 
  manager.addDocument('en', 'howdy', 'greetings.hello');

  manager.addDocument('en', 'now is party time', 'None');
  manager.addDocument('en', 'I want it all and I want it now', 'None');
  await manager.train();
  let response = await manager.process('how it the weather now?');
  console.log(response)

```
This will return an equal probability of classes, so the intent is None, caused because the feautres of the utterance are not present in the model:
```
  classification:
   [ { label: 'greetings.bye', value: 0.5 },
     { label: 'greetings.hello', value: 0.5 } ],
  intent: 'None',
  domain: 'default',
  score: 1
```

**Second approach**: Train an intent None with sentences with now and others to avoid the bias:

```
  manager.addDocument('en', 'goodbye for now', 'greetings.bye'); 
  manager.addDocument('en', 'bye bye take care', 'greetings.bye'); 
  manager.addDocument('en', 'okay see you later', 'greetings.bye'); 
  manager.addDocument('en', 'bye for now', 'greetings.bye'); 
  manager.addDocument('en', 'i must go', 'greetings.bye'); 
  
  manager.addDocument('en', 'hello', 'greetings.hello'); 
  manager.addDocument('en', 'hi', 'greetings.hello'); 
  manager.addDocument('en', 'howdy', 'greetings.hello');

  manager.addDocument('en', 'now is party time', 'None');
  manager.addDocument('en', 'I want it all and I want it now', 'None');
```
This will answer an intent None with a probability different to 1, but higher than the others:

```
  classification:
   [ { label: 'None', value: 0.9573729567776742 },
     { label: 'greetings.bye', value: 0.3429268473012463 },
     { label: 'greetings.hello', value: 0.025814623150808652 } ],
  intent: 'None',
  domain: 'default',
  score: 0.9573729567776742,
```

**Comment by mheimschild** [comment] 2018-10-29 08:07
@jesus-seijas-sp thank you for your detailed response!
My use case behind this problem it to recognise only two tinny intents and provide a generic response if none of these two were recognised.
I found out that if I keep sample documents simple - without any unnecessary words - this solution works perfectly.
For all other cases I will define keywords as a text entities and expect them being recognised additionally to the recognised intent

**Comment by jesus-seijas-sp** [comment] 2019-09-05 12:12
Closing as the new classifier takes into account the false positives

**Closed by jesus-seijas-sp** 2019-09-05 12:12 UTC

**Comment by etiennellipse** [comment] 2020-01-14 21:42
@jesus-seijas-sp Very useful comment; definitely the kind of information that would be nice in the documentation. Thanks.
