### ISSUE TITLE
Classifications not working as expected with multi-words NamedEntities.

### ISSUE THREAD

**Issue by Jamerrone** [axa-group/nlp.js#385] opened 2020-02-06 15:51 UTC
## Summary

The NLP manager is making totally broken and unrelated classifications with multi-words NamedEntities.

## Simplest Example to Reproduce
```
manager.addNamedEntityText("size", "grande", ["en", "nl"], ["Grande", "Large", "Triple", "Grote", "Groot"]);
manager.addNamedEntityText("size", "short", ["en", "nl"], ["Short", "Small", "Single", "Kleine", "Klein"]);
manager.addNamedEntityText("size", "tall", ["en", "nl"], ["Tall", "Medium", "Double"]);
```

```
manager.addNamedEntityText("drink", "caffeAmericano", ["en", "nl"], ["Caffè Americano", "Caffè Americanos", "Americano", "Americanos"]);
manager.addNamedEntityText("drink", "caffèLatte", ["en", "nl"], ["Caffè Latte", "Caffè Lattes", "Latte", "Lattes"]);
manager.addNamedEntityText("drink", "caffèMocha", ["en", "nl"], ["Caffè Mocha", "Caffè Mochas", "Mocha", "Mochas"]);
manager.addNamedEntityText("drink", "cappuccino", ["en", "nl"], ["Cappuccino", "Cappuccinos"]);
manager.addNamedEntityText("drink", "caramelMacchiato", ["en", "nl"], ["Caramel Macchiato", "Caramel Macchiatos"]);
manager.addNamedEntityText("drink", "espresso", ["en", "nl"], ["Espresso", "Espressos"]);
manager.addNamedEntityText("drink", "espressoConPanna", ["en", "nl"], ["Espresso Con Panna", "Espressos Con Panna"]);
manager.addNamedEntityText("drink", "espressoMacchiato", ["en", "nl"], ["Espresso Macchiato", "Espresso Macchiatos", "Macchiato", "Macchiatos"]);
manager.addNamedEntityText("drink", "whiteChocolateMocha", ["en", "nl"], ["White Chocolate Mocha", "White Chocolate Mochas"]);
```

```
manager.addDocument("en", "%drink%.", "Order");
manager.addDocument("en", "%size% %drink%.", "Order");
manager.addDocument("en", "And one %drink%.", "Order");
manager.addDocument("en", "And one %size% %drink%.", "Order");
manager.addDocument("en", "Can I get a %drink% please?", "Order");
manager.addDocument("en", "Can I get a %size% %drink% please?", "Order");
manager.addDocument("en", "Can I order a %drink% please?", "Order");
manager.addDocument("en", "Can I order a %size% %drink% please?", "Order");
manager.addDocument("en", "Finally one %drink%.", "Order");
manager.addDocument("en", "Finally one %size% %drink%.", "Order");
manager.addDocument("en", "Give me a %drink%.", "Order");
manager.addDocument("en", "Give me a %size% %drink%.", "Order");
manager.addDocument("en", "I want a %drink%.", "Order");
manager.addDocument("en", "I want a %size% %drink%.", "Order");
manager.addDocument("en", "Lastly one %drink%.", "Order");
manager.addDocument("en", "Lastly one %size% %drink%.", "Order");
manager.addDocument("en", "One %drink%.", "Order");
manager.addDocument("en", "One %size% %drink%.", "Order");
manager.addDocument("nl", "%drink%.", "Order");
manager.addDocument("nl", "%size% %drink%.", "Order");
manager.addDocument("nl", "Een %drink%.", "Order");
manager.addDocument("nl", "Een %size% %drink%.", "Order");
manager.addDocument("nl", "En een %drink%.", "Order");
manager.addDocument("nl", "En een %size% %drink%.", "Order");
manager.addDocument("nl", "En tot slot een %drink%.", "Order");
manager.addDocument("nl", "En tot slot een %size% %drink%.", "Order");
manager.addDocument("nl", "Geef me een %drink%.", "Order");
manager.addDocument("nl", "Geef me een %size% %drink%.", "Order");
manager.addDocument("nl", "Ik wil een %drink%.", "Order");
manager.addDocument("nl", "Ik wil een %size% %drink%.", "Order");
manager.addDocument("nl", "Kan ik alstublieft één %drink% krijgen?", "Order");
manager.addDocument("nl", "Kan ik een %drink% bestellen?", "Order");
manager.addDocument("nl", "Kan ik een %size% %drink% bestellen?", "Order");
manager.addDocument("nl", "Mag ik een %size% %drink%?", "Order");
manager.addDocument("nl", "Ten slotte een %drink%.", "Order");
manager.addDocument("nl", "Ten slotte een %size% %drink%.", "Order");
```

Utterance: `Give me a White Chocolate Mocha.`.
Expected Result:
```
{
  "intent": "Order",
  "score": 1
}
```
Received Result:
```
{
  "intent": "None",
  "score": 0.9831538856012558
}
```

It works just fine with single words like the sizes and `espresso`, `latte`, etc.

## Your Environment
| Software             | Version |
|----------------------|---------|
| `nlp.js`   | v4.0.2 |
| `node`               | v13.3.0        |
| `npm`                | v6.13.1        |
| Operating System     | MacOS         |

**Comment by jesus-seijas-sp** [comment] 2020-02-06 16:04
Hello,

Perhaps you didn't await for the train... 
Here you have your example running online in runkit, you can see that the answer is the expected one (Order) with score 1 and the two entities:
https://runkit.com/jesus-seijas-sp/5e3c37dde22bd400139a8346

**Comment by jesus-seijas-sp** [comment] 2020-02-06 16:07
The answer in the runkit:

![image](https://user-images.githubusercontent.com/15154218/73955131-256f4480-4903-11ea-87a4-b7aa27b97c10.png)

**Comment by Jamerrone** [comment] 2020-02-06 16:10
Hey. Thanks for your fast reply, this is strange. Here is my complete file:

```
const { NlpManager } = require("node-nlp");
const manager = new NlpManager({ languages: ["en", "nl"], threshold: 0.90 });

manager.addNamedEntityText("size", "grande", ["en", "nl"], ["Grande", "Large", "Triple", "Grote", "Groot"]);
manager.addNamedEntityText("size", "short", ["en", "nl"], ["Short", "Small", "Single", "Kleine", "Klein"]);
manager.addNamedEntityText("size", "tall", ["en", "nl"], ["Tall", "Medium", "Double"]);

manager.addNamedEntityText("drink", "caffeAmericano", ["en", "nl"], ["Caffè Americano", "Caffè Americanos", "Americano", "Americanos"]);
manager.addNamedEntityText("drink", "caffèLatte", ["en", "nl"], ["Caffè Latte", "Caffè Lattes", "Latte", "Lattes"]);
manager.addNamedEntityText("drink", "caffèMocha", ["en", "nl"], ["Caffè Mocha", "Caffè Mochas", "Mocha", "Mochas"]);
manager.addNamedEntityText("drink", "cappuccino", ["en", "nl"], ["Cappuccino", "Cappuccinos"]);
manager.addNamedEntityText("drink", "caramelMacchiato", ["en", "nl"], ["Caramel Macchiato", "Caramel Macchiatos"]);
manager.addNamedEntityText("drink", "espresso", ["en", "nl"], ["Espresso", "Espressos"]);
manager.addNamedEntityText("drink", "espressoConPanna", ["en", "nl"], ["Espresso Con Panna", "Espressos Con Panna"]);
manager.addNamedEntityText("drink", "espressoMacchiato", ["en", "nl"], ["Espresso Macchiato", "Espresso Macchiatos", "Macchiato", "Macchiatos"]);
manager.addNamedEntityText("drink", "whiteChocolateMocha", ["en", "nl"], ["White Chocolate Mocha", "White Chocolate Mochas"]);

manager.addDocument("en", "%drink%.", "Order");
manager.addDocument("en", "%size% %drink%.", "Order");
manager.addDocument("en", "And one %drink%.", "Order");
manager.addDocument("en", "And one %size% %drink%.", "Order");
manager.addDocument("en", "Can I get a %drink% please?", "Order");
manager.addDocument("en", "Can I get a %size% %drink% please?", "Order");
manager.addDocument("en", "Can I order a %drink% please?", "Order");
manager.addDocument("en", "Can I order a %size% %drink% please?", "Order");
manager.addDocument("en", "Finally one %drink%.", "Order");
manager.addDocument("en", "Finally one %size% %drink%.", "Order");
manager.addDocument("en", "Give me a %drink%.", "Order");
manager.addDocument("en", "Give me a %size% %drink%.", "Order");
manager.addDocument("en", "I want a %drink%.", "Order");
manager.addDocument("en", "I want a %size% %drink%.", "Order");
manager.addDocument("en", "Lastly one %drink%.", "Order");
manager.addDocument("en", "Lastly one %size% %drink%.", "Order");
manager.addDocument("en", "One %drink%.", "Order");
manager.addDocument("en", "One %size% %drink%.", "Order");
manager.addDocument("nl", "%drink%.", "Order");
manager.addDocument("nl", "%size% %drink%.", "Order");
manager.addDocument("nl", "Een %drink%.", "Order");
manager.addDocument("nl", "Een %size% %drink%.", "Order");
manager.addDocument("nl", "En een %drink%.", "Order");
manager.addDocument("nl", "En een %size% %drink%.", "Order");
manager.addDocument("nl", "En tot slot een %drink%.", "Order");
manager.addDocument("nl", "En tot slot een %size% %drink%.", "Order");
manager.addDocument("nl", "Geef me een %drink%.", "Order");
manager.addDocument("nl", "Geef me een %size% %drink%.", "Order");
manager.addDocument("nl", "Ik wil een %drink%.", "Order");
manager.addDocument("nl", "Ik wil een %size% %drink%.", "Order");
manager.addDocument("nl", "Kan ik alstublieft één %drink% krijgen?", "Order");
manager.addDocument("nl", "Kan ik een %drink% bestellen?", "Order");
manager.addDocument("nl", "Kan ik een %size% %drink% bestellen?", "Order");
manager.addDocument("nl", "Mag ik een %size% %drink%?", "Order");
manager.addDocument("nl", "Ten slotte een %drink%.", "Order");
manager.addDocument("nl", "Ten slotte een %size% %drink%.", "Order");

manager.addDocument("en", "%size%", "Order.Size");
manager.addDocument("en", "A %size% one.", "Order.Size");
manager.addDocument("nl", "%size%", "Order.Size");
manager.addDocument("nl", "Een %size%.", "Order.Size");
manager.addAnswer("en", "Order.Size", "Sorry, I could not understand, please rephrase your previous message.");
manager.addAnswer("nl", "Order.Size", "Sorry, ik kon het niet begrijpen, herformuleer je vorige bericht.");

manager.addDocument("en", "Clear order.", "Order.Reset");
manager.addDocument("en", "Reset.", "Order.Reset");
manager.addDocument("en", "Restart.", "Order.Reset");
manager.addDocument("en", "Start over.", "Order.Reset");
manager.addDocument("nl", "Begin opnieuw.", "Order.Reset");
manager.addDocument("nl", "Bestelling wissen.", "Order.Reset");
manager.addDocument("nl", "Herstarten.", "Order.Reset");
manager.addDocument("nl", "Reset.", "Order.Reset");
manager.addAnswer("en", "Order.Reset", "Let's start over. What would you like to order?")
manager.addAnswer("nl", "Order.Reset", "Laten we opnieuw beginnen. Wat zou u willen bestellen?")

manager.addAnswer("en", "None", "Sorry, I could not understand, please rephrase your previous message.");
manager.addAnswer("nl", "None", "Sorry, ik kon het niet begrijpen, herformuleer je vorige bericht.");

exports.handler = async function(event) {
  try {
    const route = event.path
      .replace(/^\/\.netlify\/functions/, "")
      .replace(/^\/[a-z-]+/, "")
      .replace(/^\//, "")
      .replace(/-/g, " ")
      .split("/");

    // await manager.train();
    // manager.save();
    manager.load();

    const nlpResponse = await manager.process(route[0], route[1]);

    return {
      statusCode: 200,
      body: await JSON.stringify(nlpResponse, null, 2)
    };
  } catch (error) {
    console.log(error);

    return {
      statusCode: 500,
      body: JSON.stringify({ msg: error.message }, null, 2)
    };
  }
};
```

I will look into it.

**Comment by jesus-seijas-sp** [comment] 2020-02-06 16:15
const manager = new NlpManager({
    languages: ['en', 'nl'],
    **nlu: { useNoneFeature: false,** log: false },
  });

This. The problem is that the entities are considered as non existing words in the training corpora... this is a bug.  That means that every word from an entity has a little weight to the intent None. Right now you can deactivate the useNoneFeature so this weight will be 0, until I fix it (basically I will add the words from entities to the dictionary of valid words).

**Comment by Jamerrone** [comment] 2020-02-06 16:17
thank you, this works. i will be looking forward to the update.

**Comment by obaid** [comment] 2020-04-27 09:10
@jesus-seijas-sp and @Jamerrone 

I am running into an issue with the example code here:

When I change the utterance to:

` const result = await manager.process('White Chocolate Mocha');`

which is just the entity value and should match with intent `Order` but I get `None`

If I do:
`const result = await manager.process('en', 'and one White Chocolate Mocha');` 
then I get the correct intent 'Order` back.

Any idea why?

**Comment by obaid** [comment] 2020-04-27 09:11
btw this was working fine till version 3.9.0

**Comment by Apollon77** [comment] 2022-08-08 20:00
This should be fixed in the meantime

**Comment by aigloss** [comment] 2022-11-25 09:13
Closing due to inactivity. Please, re-open if you think the topic is still alive.

**Closed by aigloss** 2022-11-25 09:13 UTC
